from playwright.sync_api import Page, expect


def test_demo_qa(page: Page):
    page.goto("https://demoqa.com/automation-practice-form")
    first_name_field = page.get_by_placeholder("First Name")
    first_name_field.fill("Ivan")
    last_name_field = page.get_by_placeholder("Last Name")
    last_name_field.fill("Ivanov")
    email_field = page.get_by_placeholder("name@example.com")
    email_field.fill("ivanov@gmail.com")
    gender_radiobutton = page.locator('[value="Male"]')
    gender_radiobutton.click()
    mobile_number_field = page.get_by_placeholder("Mobile Number")
    mobile_number_field.fill("1234567890")
    date_of_birth = page.locator("#dateOfBirthInput")
    date_of_birth.click()
    month_of_birth = page.locator(".react-datepicker__month-select")
    month_of_birth.select_option("January")
    year_of_birth = page.locator(".react-datepicker__year-select")
    year_of_birth.select_option("1989")
    day_of_birth = page.get_by_role("gridcell", name="20")
    day_of_birth.click()
    subjects_field_1 = page.locator("#subjectsInput")
    subjects_field_1.fill("comp")
    subjects_field_1_choose = page.locator(".subjects-auto-complete__menu")
    subjects_field_1_choose.click()
    subjects_field_2 = page.locator("#subjectsInput")
    subjects_field_2.fill("eco")
    subjects_field_2_choose = page.locator(".subjects-auto-complete__menu")
    subjects_field_2_choose.click()
    hobbies = page.get_by_label("Sports")
    hobbies.click()
    address = page.get_by_placeholder("Current Address")
    address.fill("Washington str, 10")
    state = page.locator("#react-select-3-input")
    state.fill("NCR")
    state.press("Enter")
    city = page.locator("#react-select-4-input")
    city.fill("Delhi")
    city.press("Enter")
    submit = page.get_by_text("Submit")
    submit.click()
    expect(page.get_by_text("Thanks for submitting the form"))
